<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Posted</name>
   <tag></tag>
   <elementGuidId>d9e4f7ed-6985-440e-b979-e97f82697801</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cph1_rwGridView&quot;)/tbody[1]/tr[2]/td[10]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administration/FinancialMapping/CompanyPreNonMapping.aspx?CompanyID=1000376&amp;Type=1200190000&amp;FillingDate=1/6/2017 12:00:00 AM&amp;PeriodType=43</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Posted</value>
   </webElementProperties>
</WebElementEntity>
