<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ctl00cph1CompanyLocatio (1)</name>
   <tag></tag>
   <elementGuidId>2178bf12-29e5-48e1-9144-f54a594fe756</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cph1_CompanyLocationViews1_CompanyLocationAdd_ctrlCompanyLocation_ddlState&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cph1$CompanyLocationViews1$CompanyLocationAdd$ctrlCompanyLocation$ddlState</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$cph1$CompanyLocationViews1$CompanyLocationAdd$ctrlCompanyLocation$ddlState\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cph1_CompanyLocationViews1_CompanyLocationAdd_ctrlCompanyLocation_ddlState</value>
   </webElementProperties>
</WebElementEntity>
