<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ctl00cph1AcquisitionVie (2)</name>
   <tag></tag>
   <elementGuidId>b4b61425-fbd5-4446-ae25-8ad5e74b5733</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cph1_AcquisitionView1_AcquisitionAdd_AcquisitionInfo1_ddlTypeOfAcquisition&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cph1$AcquisitionView1$AcquisitionAdd$AcquisitionInfo1$ddlTypeOfAcquisition</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cph1_AcquisitionView1_AcquisitionAdd_AcquisitionInfo1_ddlTypeOfAcquisition</value>
   </webElementProperties>
</WebElementEntity>
